language: python

python:
- "3.6"

install:
- pip install pipenv --upgrade
- pipenv install --dev --skip-lock

script:
- pipenv run coverage run --source src -m pytest

cache: pip

after_success:
- coveralls